version: "3.1"
services:
  postgres:
    container_name: db
    image: postgres:17
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: n8n
    ports:
      - 5432:5432
    volumes:
      - ./postgres:/var/lib/postgresql/data
  n8n:
    container_name: n8n
    image: docker.n8n.io/n8nio/n8n:1.88.0
    restart: always
    ports:
      - 5678:5678
    environment:
      DB_TYPE: postgresdb
      DB_POSTGRESDB_DATABASE: n8n
      DB_POSTGRESDB_HOST: postgres
      DB_POSTGRESDB_PORT: 5432
      DB_POSTGRESDB_USER: postgres
      DB_POSTGRESDB_PASSWORD: postgres
      DB_POSTGRESDB_SCHEMA: public
      GENERIC_TIMEZONE: "Asia/Bangkok"
      TZ: "Asia/Bangkok"
    volumes:
      - n8n_data:/home/node/.n8n
    depends_on:
      - postgres

volumes:
  n8n_data:
    external: true
